Gazelle API improvements and dependency upgrade
ahdis/matchbox pull request #223
Opened 2024-04-19 07:15 UTC by qligier

2024-04-19 08:20 UTC, oliveregger commented on matchbox-engine/src/main/java/org/hl7/fhir/r5/utils/structuremap/FFHIRPathHostServices.java
why is this file removed?

2024-04-19 08:23 UTC, qligier commented on matchbox-engine/src/main/java/org/hl7/fhir/r5/utils/structuremap/FFHIRPathHostServices.java
It was renamed because there was a typo in the name: https://github.com/hapifhir/org.hl7.fhir.core/commit/82813a88d25a9b06fb41db0035da861d44801ce8#diff-b26d7bf9d75c30c0788d5b10cdfc40439a3091a54ea70bb100d9d215cf53c357
We still have FHIRPathHostServices.java

2024-04-19 08:25 UTC, oliveregger requested changes
why do we have spacing / tab mix up? if would be nicer to see only the changes for the files we make to them we have originally from hapi-fhir. or are they currently wrong in our source?

2024-04-19 08:26 UTC, oliveregger commented on matchbox-engine/src/main/java/org/hl7/fhir/r5/utils/structuremap/FFHIRPathHostServices.java
but then the need to add the conformsTo function from the old one:

	@Override
	public boolean conformsToProfile(FHIRPathEngine engine, Object appContext, Base item, String url)
			throws FHIRException {
		//IResourceValidator val = structureMapUtilities.getWorker().newValidator();
		// we need the same conformToProfile context as we have in the matchbox engine
		// matchbox 3.1.0
		 InstanceValidator val = null;
		 try {
			val = ((ch.ahdis.matchbox.mappinglanguage.MatchboxStructureMapUtilities) structureMapUtilities).getEngine().getValidator(
				Manager.FhirFormat.JSON);
		 } catch (IOException e) {
			throw new NotImplementedException("Not done yet (FFHIRPathHostServices.conformsToProfile), engine could not be created");
		 }
		List<ValidationMessage> valerrors = new ArrayList<ValidationMessage>();
		if (item instanceof Resource) {
			val.validate(appContext, valerrors, (Resource) item, url);
			return noErrorValidationMessages(valerrors);
		}
		if (item instanceof Element) {
			val.validate(appContext, valerrors, null, (Element) item, url);
			return noErrorValidationMessages(valerrors);
		}
		throw new NotImplementedException("Not done yet (FFHIRPathHostServices.conformsToProfile), when item is not element or not resource");
	}

2024-04-19 08:31 UTC, qligier commented on matchbox-engine/src/main/java/org/hl7/fhir/r5/utils/structuremap/FFHIRPathHostServices.java
I don't understand. Both classes have the same conformsToProfile method.

2024-04-22 12:59 UTC, qligier commented
I have issues with the validation: I get "_Validation for profile '...' not supported by this server, but additional ig's could be configured_." for IGs that are loaded.
Specifying the IG fixes the issue.

I'm not sure, but profiles with versions could have the issue too, that could be the cause of the EVSClient not working this morning.

2024-04-22 13:26 UTC, oliveregger commented
> I have issues with the validation: I get "_Validation for profile '...' not supported by this server, but additional ig's could be configured_." for IGs that are loaded. Specifying the IG fixes the issue.
> 
> I'm not sure, but profiles with versions could have the issue too, that could be the cause of the EVSClient not working this morning.

that would mean we have a discrepancy between the profiles registered in the database and the loaded ig's. where did this happen? on our test matchboxv3?

2024-04-22 13:53 UTC, qligier commented
> that would mean we have a discrepancy between the profiles registered in the database and the loaded ig's. where did this happen? on our test matchboxv3?

On matchboxv3, yes.
After clearing the database, I don't have issues with my local instance.

2024-04-23 06:55 UTC, merged